git add /home/csr1/my-awi-instance/UU .claude/hooks/auto-commit.sh
git add /home/csr1/my-awi-instance/UU .claude/settings.json
git add /home/csr1/my-awi-instance/UU .claude/skills/awi-core-sync-status/scripts/sync_status.py
git add /home/csr1/my-awi-instance/UU .claude/skills/awi-initialize/scripts/init_awi.py
git add /home/csr1/my-awi-instance/UU .claude/skills/awi-introduction/SKILL.md
git add /home/csr1/my-awi-instance/UU .claude/skills/awi-sync/SKILL.md
git add /home/csr1/my-awi-instance/UU .claude/skills/awi-sync/scripts/sync_submodules.py
git add /home/csr1/my-awi-instance/UU .claude/skills/break/SKILL.md
git add /home/csr1/my-awi-instance/UU .claude/skills/delegate/SKILL.md
git add /home/csr1/my-awi-instance/UU .claude/skills/new-client/SKILL.md
git add /home/csr1/my-awi-instance/UU .claude/skills/new-client/scripts/init_client.py
git add /home/csr1/my-awi-instance/UU .claude/skills/new-client/scripts/toggle_client.py
git add /home/csr1/my-awi-instance/UU .claude/skills/new/SKILL.md
git add /home/csr1/my-awi-instance/UU .claude/skills/quarter/SKILL.md
git add /home/csr1/my-awi-instance/UU .claude/skills/shared/scripts/log_command.py
git add /home/csr1/my-awi-instance/UU .claude/skills/today-end/SKILL.md
git add /home/csr1/my-awi-instance/UU .claude/skills/today-start/SKILL.md
git add /home/csr1/my-awi-instance/UU .claude/skills/today/SKILL.md
git add /home/csr1/my-awi-instance/UU .claude/skills/week-review/SKILL.md
git add /home/csr1/my-awi-instance/UU .claude/skills/week/SKILL.md
git add /home/csr1/my-awi-instance/UU .claude/skills/wrap-session/SKILL.md
git add /home/csr1/my-awi-instance/UU .claude/skills/year/SKILL.md
git add /home/csr1/my-awi-instance/UU AGENTS.md
git add /home/csr1/my-awi-instance/UU CLAUDE.md
git add /home/csr1/my-awi-instance/UU _system/chief-of-staff/references/documentation/classification.md
git add /home/csr1/my-awi-instance/UU _system/chief-of-staff/references/examples/commands.md
git add /home/csr1/my-awi-instance/UU _system/chief-of-staff/references/examples/troubleshooting.md
git add /home/csr1/my-awi-instance/UU _system/chief-of-staff/references/tools/git-audit-trail.md
git add /home/csr1/my-awi-instance/UU _system/chief-of-staff/references/tools/hooks.md
